export enum EventType {
  FIRE = 'FIRE',
  TYPHOON = 'TYPHOON',
  EARTHQUAKE = 'EARTHQUAKE',
  WAR = 'WAR',
  FLOOD = 'FLOOD',
  ACCIDENT = 'ACCIDENT',
  CAR_ACCIDENT = 'CAR_ACCIDENT',
  OTHER = 'OTHER',
  NONE = 'NONE',
}
