export enum NotificationType {
  FAVORITE_REQUEST = 'FAVORITE_REQUEST',
  FAVORITE_ACCEPT = 'FAVORITE_ACCEPT',
  NEARBY_EVENT = 'NEARBY_EVENT',
  HELP_REQUEST = 'HELP_REQUEST',
  FAVORITE_NEARBY_EVENT = 'FAVORITE_NEARBY_EVENT',
}
